development:
  adapter: postgresql
  database: my_database
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: postgres
  password: postgres

test: 
  adapter: postgresql
  database: my_database
  pool: 5
  timeout: 5000
  username: postgres 
  password: postgres

production:
  adapter: postgresql
  database: my_database
  pool: 5
  timeout: 3000
  username: postgres 
  password: postgres